apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler
    spec:
      initContainers:
        - name: init-catalog-app
          image: busybox
          command:
          - sh
          - -c
          - 'while true; do echo "Waiting for catalog app service to come up..."; wget http://app:8000/api/pinakes/v1/ -q -T 1 -O /dev/null >/dev/null 2>/dev/null && break; sleep 1; done; echo "Service is up! Starting main container."'
      containers:
        - args:
            - "/opt/app-root/src/tools/minikube/scripts/scheduler.sh"
          env:
            - name: PINAKES_REDIS_HOST
              value: redis
            - name: PINAKES_REDIS_PORT
              value: "6379"
            - name: PINAKES_REDIS_DB
              value: "0"
            - name: PINAKES_KEYCLOAK_URL
              value: http://keycloak:8080/auth
            - name: PINAKES_KEYCLOAK_CLIENT_SECRET
              value: SOMESECRETVALUE
            - name: PINAKES_KEYCLOAK_REALM
              value: pinakes
            - name: PINAKES_KEYCLOAK_CLIENT_ID
              value: pinakes
            - name: CONTROLLER_VERIFY_SSL
              value: "False"
            - name: PINAKES_DATABASE_NAME
              value: dev_catalog
            - name: PINAKES_POSTGRES_HOST
              value: postgres
            - name: PINAKES_POSTGRES_USER
              value: keycloak
            - name: PINAKES_POSTGRES_PASSWORD
              value: password
            - name: PINAKES_ALLOWED_HOSTS
              value: "*"
            - name: PINAKES_DEBUG
              value: "True"
            - name: PINAKES_SECRET_KEY
              value: "django-insecure-k8^atj4p3jj^zkb3=o(rhaysjzy_mr&#h(yl+ytj#f%@+er4&5"
            - name: PINAKES_CONTROLLER_URL
              valueFrom:
                configMapKeyRef:
                  name: ansible-controller-env
                  key: PINAKES_CONTROLLER_URL
            - name: PINAKES_CONTROLLER_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: ansible-controller-env
                  key: PINAKES_CONTROLLER_TOKEN
            - name: PINAKES_CONTROLLER_VERIFY_SSL
              valueFrom:
                configMapKeyRef:
                  name: ansible-controller-env
                  key: PINAKES_CONTROLLER_VERIFY_SSL
            - name: PINAKES_INSIGHTS_TRACKING_STATE
              valueFrom:
                configMapKeyRef:
                  name: ansible-insights-env
                  key: PINAKES_INSIGHTS_TRACKING_STATE
            - name: PINAKES_INSIGHTS_URL
              valueFrom:
                configMapKeyRef:
                  name: ansible-insights-env
                  key: PINAKES_INSIGHTS_URL
            - name: PINAKES_INSIGHTS_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  name: ansible-insights-env
                  key: PINAKES_INSIGHTS_AUTH_METHOD
            - name: PINAKES_INSIGHTS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ansible-insights-env
                  key: PINAKES_INSIGHTS_USERNAME
            - name: PINAKES_INSIGHTS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ansible-insights-env
                  key: PINAKES_INSIGHTS_PASSWORD
          image: localhost/pinakes
          imagePullPolicy: Never
          name: scheduler
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: scheduler-claim0
      restartPolicy: Always
      volumes:
        - name: scheduler-claim0
          persistentVolumeClaim:
            claimName: scheduler-claim0
status: {}
